allow building only plugins

diff --git a/build-guh b/build-guh
--- a/build-guh
+++ b/build-guh
@@ -41,22 +41,35 @@ TEMPLATEDIR=$BASEDIR/templates
 source $BASEDIR/build-tools
 
 # prepare source code (check out all repos next to each other)
+HAVE_BRANCH=0
 git clone https://github.com/guh/guh.git
-cd guh
-git merge origin/$GIT_BRANCH
-
-cd ..
-git clone https://github.com/guh/guh-plugins.git
-cd guh-plugins
 set +e
-git merge origin/$GIT_BRANCH
+git -C guh merge origin/$GIT_BRANCH
+RESULT=$$
+set -e
+if [ $RESULT -ne 0 ]; then
+  echo No corresponding guh branch found. Building master...
+  git -C guh checkout master
+else
+  HAVE_BRANCH=1
+fi
+
+git clone https://github.com/guh/guh-plugins.git
+set +e
+git -C guh-plugins merge origin/$GIT_BRANCH
 RESULT=$?
 set -e
 if [ $RESULT -ne 0 ]; then
   echo No corresponding plugins branch found. Building master...
-  git checkout master
+  git -C guh-plugins checkout master
+else
+  HAVE_BRANCH=1
 fi
-cd ..
+
+if [ $HAVE_BRANCH -eq 0 ]; then
+  echo "Neither guh nor guh-plugins have a branch named $GIT_BRANCH. Cannot continue."
+  exit 1
+fi
 
 cd guh && dch --release "Jenkins release" && cd ..
 cd guh-plugins && dch --release "Jenkins release" && cd ..
